In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data = pd.read_csv('/content/drive/My Drive/cannabis.csv')
data.shape

(2351, 6)

In [ ]:
data.head()

Strain  ...                                        Description
0          100-Og  ...  $100 OG is a 50/50 hybrid strain that packs a ...
1  98-White-Widow  ...  The ‘98 Aloha White Widow is an especially pot...
2            1024  ...  1024 is a sativa-dominant hybrid bred in Spain...
3        13-Dawgs  ...  13 Dawgs is a hybrid of G13 and Chemdawg genet...
4        24K-Gold  ...  Also known as Kosher Tangie, 24k Gold is a 60%...

[5 rows x 6 columns]

In [ ]:
data.isnull().sum()

Strain          0
Type            0
Rating          0
Effects         0
Flavor         46
Description    33
dtype: int64

In [ ]:
data['Flavor'] = data['Flavor'].replace(np.nan, 'Flavor information now is unavailable. ')
data['Description'] = data['Description'].replace(np.nan, 'Description information is unknown.')

In [ ]:
data['Effects'].str.lower().str.split(',').str.len().value_counts()

5    2180
1      97
4      32
3      27
2      15
Name: Effects, dtype: int64

In [ ]:
data_effects = set()
for row in data['Effects'].str.lower().str.split(','):
  data_effects.update(set(row))
len(data_effects), data_effects

(16,
 {'aroused',
  'creative',
  'dry',
  'energetic',
  'euphoric',
  'focused',
  'giggly',
  'happy',
  'hungry',
  'mouth',
  'none',
  'relaxed',
  'sleepy',
  'talkative',
  'tingly',
  'uplifted'})

In [ ]:
data_flavor = set()
for row in data['Flavor'].str.lower().str.split(','):
  data_flavor.update(set(row))
len(data_flavor), data_flavor

(51,
 {'ammonia',
  'apple',
  'apricot',
  'berry',
  'blue',
  'blueberry',
  'butter',
  'cheese',
  'chemical',
  'chestnut',
  'citrus',
  'coffee',
  'diesel',
  'earthy',
  'flavor information now is unavailable. ',
  'flowery',
  'fruit',
  'grape',
  'grapefruit',
  'honey',
  'lavender',
  'lemon',
  'lime',
  'mango',
  'menthol',
  'mint',
  'minty',
  'none',
  'nutty',
  'orange',
  'peach',
  'pear',
  'pepper',
  'pine',
  'pineapple',
  'plum',
  'pungent',
  'rose',
  'sage',
  'skunk',
  'spicy/herbal',
  'strawberry',
  'sweet',
  'tar',
  'tea',
  'tobacco',
  'tree',
  'tropical',
  'vanilla',
  'violet',
  'woody'})

In [ ]:
len(data['Strain'].unique())

2350

In [ ]:
data['Type'].value_counts()

hybrid    1212
indica     699
sativa     440
Name: Type, dtype: int64

In [ ]:
data.dtypes

Strain          object
Type            object
Rating         float64
Effects         object
Flavor          object
Description     object
dtype: object

In [ ]:
# Create a master profile feature
data['Profile'] = data['Type'] + ',' + data['Effects'] + ',' +  data['Flavor'] + ',' + str(data['Rating'])

In [ ]:
data['Profile'][1]

'hybrid,Relaxed,Aroused,Creative,Happy,Energetic,Flowery,Violet,Diesel,0       4.0\n1       4.7\n2       4.4\n3       4.2\n4       4.6\n       ... \n2346    4.7\n2347    4.6\n2348    5.0\n2349    4.4\n2350    4.6\nName: Rating, Length: 2351, dtype: float64'

#KNN Model

In [ ]:
import spacy.cli
spacy.cli.download('en_core_web_sm')

✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_sm')


In [ ]:
nlp = spacy.load('en_core_web_sm')

In [ ]:
X = [nlp(str(item)).vector for item in data['Profile']]

In [ ]:
df = pd.DataFrame(X)
df.shape

(2351, 96)

In [ ]:
df.head()

0         1         2   ...        93        94        95
0  0.354726 -1.214044  0.558231  ... -0.725212  0.292572  0.334034
1  0.345807 -1.163711  0.503540  ... -0.606200  0.427626  0.363346
2  0.402839 -1.026178  0.376286  ... -0.693737  0.324018  0.345734
3  0.191648 -1.099868  0.447670  ... -0.492892  0.254657  0.326938
4  0.433720 -1.127400  0.528763  ... -0.624086  0.262207  0.245549

[5 rows x 96 columns]

In [ ]:
from sklearn.neighbors import NearestNeighbors

In [ ]:
nn = NearestNeighbors(n_neighbors=3, algorithm='ball_tree')
nn.fit(df)

NearestNeighbors(algorithm='ball_tree', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                 radius=1.0)

In [ ]:
import pickle

In [ ]:
pickle.dump(nn, open('model.pkl', 'wb'))

In [ ]:
# Test model
test = 'hybrid relaxed spicy'
test_vect = nlp(test).vector
vect=test_vect.reshape(1,-1)
# vect.shape
# print(len(test_vect))
# test_df = pd.DataFrame(test_vect).transpose()
result = nn.kneighbors(vect)

In [ ]:
result

(array([[13.79570682, 13.79914151, 13.80494399]]), array([[ 743,  791, 1872]]))

In [ ]:
result[1]

array([[ 743,  791, 1872]])

In [ ]:
result[1][0]

array([ 743,  791, 1872])

In [ ]:
names = [data['Strain'].iloc[x] for x in result[1][0]]

In [ ]:
names

['Ebola-7', 'Fire-Alien-Strawberry', 'Silverfalls-Kush']

In [ ]:
for item in result[1][0]:
  print (f"{data['Strain'].iloc[item]}\n")

Ebola-7

Fire-Alien-Strawberry

Silverfalls-Kush

